/**
 * Design System Showcase Page Template
 *
 * This is a template for the design system page generated by /pilot-design.
 * Copy this to src/app/design-system/page.tsx and customize as needed.
 *
 * Generated by Pilot AGI v0.4.0
 */

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Separator } from "@/components/ui/separator";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

export default function DesignSystemPage() {
  return (
    <div className="container mx-auto py-10 space-y-16 max-w-5xl">
      {/* Header */}
      <header className="space-y-4">
        <h1 className="text-4xl font-bold tracking-tight">Design System</h1>
        <p className="text-xl text-muted-foreground">
          Component library and design tokens for {{PROJECT_NAME}}.
        </p>
        <div className="flex gap-2">
          <Badge>v1.0.0</Badge>
          <Badge variant="outline">shadcn/ui</Badge>
          <Badge variant="secondary">Tailwind CSS</Badge>
        </div>
      </header>

      <Separator />

      {/* Table of Contents */}
      <nav className="space-y-2">
        <h2 className="text-lg font-semibold">Contents</h2>
        <ul className="grid grid-cols-2 md:grid-cols-4 gap-2 text-sm">
          <li><a href="#colors" className="text-muted-foreground hover:text-foreground">Colors</a></li>
          <li><a href="#typography" className="text-muted-foreground hover:text-foreground">Typography</a></li>
          <li><a href="#buttons" className="text-muted-foreground hover:text-foreground">Buttons</a></li>
          <li><a href="#inputs" className="text-muted-foreground hover:text-foreground">Inputs</a></li>
          <li><a href="#cards" className="text-muted-foreground hover:text-foreground">Cards</a></li>
          <li><a href="#badges" className="text-muted-foreground hover:text-foreground">Badges</a></li>
          <li><a href="#alerts" className="text-muted-foreground hover:text-foreground">Alerts</a></li>
          <li><a href="#spacing" className="text-muted-foreground hover:text-foreground">Spacing</a></li>
        </ul>
      </nav>

      <Separator />

      {/* Colors Section */}
      <section id="colors" className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold">Colors</h2>
          <p className="text-muted-foreground">Semantic color tokens for consistent theming.</p>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <ColorSwatch name="Background" variable="--color-background" className="bg-background border" textClass="text-foreground" />
          <ColorSwatch name="Foreground" variable="--color-foreground" className="bg-foreground" textClass="text-background" />
          <ColorSwatch name="Primary" variable="--color-primary" className="bg-primary" textClass="text-primary-foreground" />
          <ColorSwatch name="Secondary" variable="--color-secondary" className="bg-secondary" textClass="text-secondary-foreground" />
          <ColorSwatch name="Muted" variable="--color-muted" className="bg-muted" textClass="text-muted-foreground" />
          <ColorSwatch name="Accent" variable="--color-accent" className="bg-accent" textClass="text-accent-foreground" />
          <ColorSwatch name="Destructive" variable="--color-destructive" className="bg-destructive" textClass="text-destructive-foreground" />
          <ColorSwatch name="Border" variable="--color-border" className="bg-border" textClass="text-foreground" />
        </div>
      </section>

      <Separator />

      {/* Typography Section */}
      <section id="typography" className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold">Typography</h2>
          <p className="text-muted-foreground">Type scale and font weights.</p>
        </div>

        <div className="space-y-6">
          <div className="space-y-4">
            <TypeSample size="4xl" weight="bold" label="Heading 1" />
            <TypeSample size="3xl" weight="semibold" label="Heading 2" />
            <TypeSample size="2xl" weight="semibold" label="Heading 3" />
            <TypeSample size="xl" weight="medium" label="Heading 4" />
            <TypeSample size="lg" weight="medium" label="Large text" />
            <TypeSample size="base" weight="normal" label="Body text" />
            <TypeSample size="sm" weight="normal" label="Small text" muted />
            <TypeSample size="xs" weight="normal" label="Extra small / Caption" muted />
          </div>
        </div>
      </section>

      <Separator />

      {/* Buttons Section */}
      <section id="buttons" className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold">Buttons</h2>
          <p className="text-muted-foreground">Interactive button components with multiple variants and sizes.</p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Variants</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-4">
              <Button>Default</Button>
              <Button variant="secondary">Secondary</Button>
              <Button variant="outline">Outline</Button>
              <Button variant="ghost">Ghost</Button>
              <Button variant="destructive">Destructive</Button>
              <Button variant="link">Link</Button>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Sizes</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap items-center gap-4">
              <Button size="sm">Small</Button>
              <Button size="default">Default</Button>
              <Button size="lg">Large</Button>
              <Button size="icon" aria-label="Add">
                <PlusIcon />
              </Button>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg">States</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-4">
              <Button>Normal</Button>
              <Button disabled>Disabled</Button>
            </div>
          </CardContent>
        </Card>
      </section>

      <Separator />

      {/* Inputs Section */}
      <section id="inputs" className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold">Form Inputs</h2>
          <p className="text-muted-foreground">Text inputs, checkboxes, switches, and other form controls.</p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Text Inputs</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 max-w-md">
            <div className="space-y-2">
              <Label htmlFor="default">Default Input</Label>
              <Input id="default" placeholder="Enter text..." />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" placeholder="name@example.com" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input id="password" type="password" placeholder="Enter password" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="disabled">Disabled</Label>
              <Input id="disabled" disabled placeholder="Disabled input" />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Textarea</CardTitle>
          </CardHeader>
          <CardContent className="max-w-md">
            <div className="space-y-2">
              <Label htmlFor="textarea">Description</Label>
              <Textarea id="textarea" placeholder="Enter a longer description..." />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Checkbox & Switch</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center space-x-2">
              <Checkbox id="terms" />
              <Label htmlFor="terms">Accept terms and conditions</Label>
            </div>
            <div className="flex items-center space-x-2">
              <Switch id="notifications" />
              <Label htmlFor="notifications">Enable notifications</Label>
            </div>
          </CardContent>
        </Card>
      </section>

      <Separator />

      {/* Cards Section */}
      <section id="cards" className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold">Cards</h2>
          <p className="text-muted-foreground">Content containers with header, content, and footer sections.</p>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Full Card</CardTitle>
              <CardDescription>With all sections: header, content, and footer.</CardDescription>
            </CardHeader>
            <CardContent>
              <p>Card content goes here. This can contain any type of content including text, images, or other components.</p>
            </CardContent>
            <CardFooter className="flex justify-between">
              <Button variant="outline">Cancel</Button>
              <Button>Save</Button>
            </CardFooter>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Simple Card</CardTitle>
            </CardHeader>
            <CardContent>
              <p>A simpler card with just header and content, no footer.</p>
            </CardContent>
          </Card>

          <Card className="md:col-span-2">
            <CardContent className="pt-6">
              <p className="text-center text-muted-foreground">Content-only card (no header/footer)</p>
            </CardContent>
          </Card>
        </div>
      </section>

      <Separator />

      {/* Badges Section */}
      <section id="badges" className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold">Badges</h2>
          <p className="text-muted-foreground">Status indicators and labels.</p>
        </div>

        <Card>
          <CardContent className="pt-6">
            <div className="flex flex-wrap gap-4">
              <Badge>Default</Badge>
              <Badge variant="secondary">Secondary</Badge>
              <Badge variant="outline">Outline</Badge>
              <Badge variant="destructive">Destructive</Badge>
            </div>
          </CardContent>
        </Card>
      </section>

      <Separator />

      {/* Alerts Section */}
      <section id="alerts" className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold">Alerts</h2>
          <p className="text-muted-foreground">Feedback and notification messages.</p>
        </div>

        <div className="space-y-4 max-w-2xl">
          <Alert>
            <InfoIcon />
            <AlertTitle>Default Alert</AlertTitle>
            <AlertDescription>
              This is a default informational alert message.
            </AlertDescription>
          </Alert>

          <Alert variant="destructive">
            <AlertCircleIcon />
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>
              This is a destructive alert for error messages.
            </AlertDescription>
          </Alert>
        </div>
      </section>

      <Separator />

      {/* Spacing Section */}
      <section id="spacing" className="space-y-6">
        <div>
          <h2 className="text-2xl font-semibold">Spacing Scale</h2>
          <p className="text-muted-foreground">4px base spacing scale for consistent layouts.</p>
        </div>

        <Card>
          <CardContent className="pt-6">
            <div className="space-y-3">
              {[
                { name: "space-1", rem: "0.25rem", px: "4px" },
                { name: "space-2", rem: "0.5rem", px: "8px" },
                { name: "space-3", rem: "0.75rem", px: "12px" },
                { name: "space-4", rem: "1rem", px: "16px" },
                { name: "space-6", rem: "1.5rem", px: "24px" },
                { name: "space-8", rem: "2rem", px: "32px" },
                { name: "space-12", rem: "3rem", px: "48px" },
                { name: "space-16", rem: "4rem", px: "64px" },
              ].map((space) => (
                <div key={space.name} className="flex items-center gap-4">
                  <span className="w-24 text-sm font-mono text-muted-foreground">{space.name}</span>
                  <div className="h-4 bg-primary rounded" style={{ width: space.rem }} />
                  <span className="text-xs text-muted-foreground">{space.px}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </section>

      <Separator />

      {/* Footer */}
      <footer className="text-center text-sm text-muted-foreground py-8">
        <p>Generated by Pilot AGI /pilot-design</p>
        <p className="mt-1">Last updated: {{DATE}}</p>
      </footer>
    </div>
  );
}

// Helper Components

function ColorSwatch({
  name,
  variable,
  className,
  textClass
}: {
  name: string;
  variable: string;
  className: string;
  textClass: string;
}) {
  return (
    <div className="space-y-2">
      <div className={`h-20 rounded-lg flex items-end p-2 ${className}`}>
        <span className={`text-xs font-mono ${textClass}`}>{variable}</span>
      </div>
      <p className="text-sm font-medium">{name}</p>
    </div>
  );
}

function TypeSample({
  size,
  weight,
  label,
  muted = false
}: {
  size: string;
  weight: string;
  label: string;
  muted?: boolean;
}) {
  const sizeClass = `text-${size}`;
  const weightClass = `font-${weight}`;
  const colorClass = muted ? "text-muted-foreground" : "";

  return (
    <div className="flex items-baseline gap-4">
      <span className="w-32 text-sm text-muted-foreground">{label}</span>
      <p className={`${sizeClass} ${weightClass} ${colorClass}`}>
        The quick brown fox jumps
      </p>
    </div>
  );
}

// Icons (inline SVG for template portability)

function PlusIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function InfoIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4">
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  );
}

function AlertCircleIcon() {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4">
      <circle cx="12" cy="12" r="10" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </svg>
  );
}
